--CREACION DE LA BASE DE DATOS
CREATE DATABASE CINE
GO

--USANDO LA BASE DE DATOS
USE CINE
GO

--CREACION DE TABLAS 
CREATE TABLE USUARIO(
Id_usuario INT IDENTITY(1,1) PRIMARY KEY,
Usuario varchar(45) NOT NULL,
Contraseña varchar(45) NOT NULL,
estado BIT NOT NULL DEFAULT 1,
tipo Varchar(45) DEFAULT 'usuario'
)
GO

CREATE TABLE BOLETERIA(
Id_boleteria INT IDENTITY(1,1) PRIMARY KEY,
Id_ticket INT NOT NULL,
Id_cartelera INT NOT NULL,
Id_usuario INT NOT NULL
)
GO

CREATE TABLE CARTELERA(
Id_cartelera INT IDENTITY(1,1) PRIMARY KEY,
Id_peliculas INT NOT NULL,
fecha_Inicio DATE NOT NULL,
fecha_fin DATE NOT NULL
)
GO

ALTER TABLE CARTELERA
ADD costo INT NOT NULL
GO

CREATE TABLE TICKET(
Id_ticket INT IDENTITY(1,1) PRIMARY KEY,
Costo smallmoney,
Nroasiento INT,
codigo varchar(25)
)
GO

CREATE TABLE ASIENTO(
Id_asiento INT IDENTITY(1,1) PRIMARY KEY,
Numero INT NOT NULL,
Id_sala INT NOT NULL
)
GO

CREATE TABLE SALA(
Id_sala INT IDENTITY(1,1) PRIMARY KEY,
Cantidad_Asientos INT,
Nombre varchar(25) NOT NULL
)
GO

CREATE TABLE PELICULAS(
Id_peliculas INT IDENTITY(1,1) PRIMARY KEY,
Titulo VARCHAR(45) NOT NULL,
Imagen IMAGE,
Descripcion VARCHAR(45),
Id_genero INT,
Id_sala INT
)
GO

CREATE TABLE GENERO(
Id_genero INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(25)
)
GO

ALTER TABLE PELICULAS
ADD CONSTRAINT FK_PELICULAS_GENERO
FOREIGN KEY (Id_genero) REFERENCES GENERO (Id_genero) ON DELETE CASCADE
GO

ALTER TABLE PELICULAS
ADD CONSTRAINT FK_PELICULAS_SALA
FOREIGN KEY (Id_sala) REFERENCES SALA (Id_sala) ON DELETE CASCADE
GO

ALTER TABLE ASIENTO
ADD CONSTRAINT FK_ASIENTO_SALA
FOREIGN KEY (Id_sala) REFERENCES SALA (Id_sala)
GO

ALTER TABLE CARTELERA
ADD CONSTRAINT FK_CARTELERA_PELICULAS
FOREIGN KEY (Id_peliculas) REFERENCES PELICULAS (Id_peliculas) ON DELETE CASCADE
GO

ALTER TABLE BOLETERIA
ADD CONSTRAINT FK_BOLETERIA_USUARIO
FOREIGN KEY (Id_usuario) REFERENCES USUARIO (Id_usuario)
GO

ALTER TABLE BOLETERIA
ADD CONSTRAINT FK_BOLETERIA_CARTELERA
FOREIGN KEY (Id_cartelera) REFERENCES CARTELERA (Id_cartelera) ON DELETE CASCADE
GO

ALTER TABLE BOLETERIA
ADD CONSTRAINT FK_BOLETERIA_TICKET
FOREIGN KEY (Id_ticket) REFERENCES TICKET (Id_ticket)
GO


INSERT INTO GENERO(Nombre) VALUES ('Comedia')
INSERT INTO GENERO(Nombre) VALUES ('Aventura')
INSERT INTO GENERO(Nombre) VALUES ('Terror')
INSERT INTO GENERO(Nombre) VALUES ('Accion')
INSERT INTO GENERO(Nombre) VALUES ('Musical')
INSERT INTO GENERO(Nombre) VALUES ('Drama')
INSERT INTO GENERO(Nombre) VALUES ('Romántico')

GO


INSERT INTO SALA(Cantidad_Asientos,Nombre) VALUES (50,'Sala 1')
INSERT INTO SALA(Cantidad_Asientos,Nombre) VALUES (45, 'Sala 2')
INSERT INTO SALA(Cantidad_Asientos,Nombre) VALUES (40, 'Sala 3')
INSERT INTO SALA(Cantidad_Asientos,Nombre) VALUES (30, 'Sala 4')
GO

INSERT INTO ASIENTO(Numero,Id_sala) VALUES(1,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(2,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(3,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(4,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(5,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(6,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(7,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(8,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(9,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(10,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(11,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(12,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(13,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(14,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(15,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(16,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(17,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(18,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(19,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(20,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(21,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(22,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(23,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(24,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(25,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(26,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(27,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(28,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(29,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(30,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(31,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(32,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(33,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(34,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(35,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(36,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(37,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(38,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(39,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(40,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(41,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(42,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(43,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(44,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(45,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(46,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(47,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(48,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(49,1)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(50,1)
GO

INSERT INTO ASIENTO(Numero,Id_sala) VALUES(1,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(2,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(3,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(4,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(5,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(6,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(7,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(8,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(9,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(10,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(11,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(12,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(13,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(14,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(15,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(16,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(17,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(18,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(19,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(20,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(21,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(22,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(23,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(24,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(25,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(26,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(27,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(28,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(29,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(30,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(31,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(32,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(33,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(34,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(35,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(36,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(37,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(38,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(39,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(40,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(41,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(42,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(43,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(44,2)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(45,2)
GO

INSERT INTO ASIENTO(Numero,Id_sala) VALUES(1,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(2,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(3,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(4,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(5,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(6,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(7,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(8,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(9,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(10,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(11,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(12,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(13,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(14,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(15,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(16,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(17,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(18,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(19,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(20,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(21,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(22,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(23,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(24,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(25,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(26,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(27,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(28,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(29,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(30,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(31,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(32,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(33,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(34,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(35,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(36,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(37,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(38,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(39,3)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(40,3)
GO

INSERT INTO ASIENTO(Numero,Id_sala) VALUES(1,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(2,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(3,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(4,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(5,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(6,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(7,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(8,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(9,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(10,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(11,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(12,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(13,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(14,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(15,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(16,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(17,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(18,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(19,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(20,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(21,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(22,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(23,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(24,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(25,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(26,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(27,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(28,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(29,4)
INSERT INTO ASIENTO(Numero,Id_sala) VALUES(30,4)
GO

INSERT INTO TICKET(Costo,Nroasiento,codigo) VALUES(30,4,'')
GO

INSERT INTO USUARIO (Usuario,Contraseña,tipo) VALUES('Yolvi','yolvi123','administrador')
GO

INSERT INTO USUARIO (Usuario,Contraseña,tipo) VALUES('dark','1725215512','administrador')
GO

CREATE PROCEDURE LOGUEO
@USUARIO VARCHAR(45),
@PASS VARCHAR(8),
@SALIDA SMALLINT OUTPUT
AS

IF EXISTS(SELECT * FROM USUARIO WHERE USUARIO COLLATE Latin1_General_CS_AS =@USUARIO and Contraseña COLLATE Latin1_General_CS_AS =@PASS and estado = 1)
BEGIN
	SET @SALIDA =1 --ACTIVO
END
ELSE
	BEGIN

		IF EXISTS(SELECT * FROM USUARIO WHERE USUARIO COLLATE Latin1_General_CS_AS =@USUARIO and Contraseña COLLATE Latin1_General_CS_AS=@PASS and estado = 0)
		BEGIN
			SET @SALIDA =2 --NO ESTA ACTIVO
		END
		ELSE
		BEGIN

			IF EXISTS(SELECT * FROM USUARIO WHERE USUARIO COLLATE Latin1_General_CS_AS =@USUARIO and Contraseña COLLATE Latin1_General_CS_AS <> @PASS and estado = 1)
			BEGIN
				SET @SALIDA = 3 --El usuario existe y esta activo pero su contraseña es erronea
			END
			ELSE
			BEGIN
				SET @SALIDA = 4 --NO EXISTE
			END
		END
	END
GO

CREATE PROCEDURE LIST_GENERO
AS 
SELECT Nombre FROM GENERO
ORDER BY Nombre
GO

CREATE PROCEDURE LIST_SALA
AS
SELECT Nombre FROM SALA
GO

CREATE PROCEDURE LIST_CARTELERA
AS
SELECT Titulo,Id_cartelera  FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas=PELICULAS.Id_peliculas
GO

CREATE PROCEDURE PA_SALA
@Nombre VARCHAR(25)
AS 
SELECT Id_sala FROM SALA
WHERE Nombre=@Nombre
GO

CREATE PROCEDURE PA_GENERO
@Nombre VARCHAR(25)
AS 
SELECT Id_genero FROM GENERO
WHERE Nombre=@Nombre
GO

CREATE PROCEDURE PA_ASIENTO
@IDSALA INT
AS 
SELECT Numero FROM ASIENTO
WHERE Id_sala=@IDSALA
GO

CREATE PROCEDURE PA_USUARIO
@Nombre VARCHAR(45)
AS 
SELECT Id_usuario FROM USUARIO
WHERE Usuario=@Nombre
GO

CREATE PROCEDURE PA_PELICULA
@Titulo VARCHAR(45)
AS 
SELECT Id_peliculas FROM PELICULAS
WHERE Titulo=@Titulo
GO

CREATE PROCEDURE PA_TICKET
@IDTICKET INT
AS 
SELECT Id_ticket FROM TICKET
WHERE Id_ticket=@IDTICKET
GO

CREATE PROCEDURE INSERTPELICULA
@TITULO VARCHAR(45),
@IMAGEN IMAGE,
@DESCRIPCION VARCHAR(45),
@GENEROID INT,
@SALAID INT
AS 
INSERT PELICULAS VALUES
(@TITULO, @IMAGEN, @DESCRIPCION, @GENEROID, @SALAID)
GO

CREATE PROCEDURE LIST_PELICULA
AS 
SELECT Titulo FROM PELICULAS
ORDER BY Titulo
GO

CREATE PROCEDURE LIST_ASIENTOS
AS 
SELECT Numero FROM ASIENTO
GO

CREATE PROCEDURE INSERTCARTELERA
@IDPELICULA INT,
@FINICIO DATE,
@FFIN DATE,
@COST INT
AS 
INSERT CARTELERA VALUES
(@IDPELICULA, @FINICIO, @FFIN, @COST)
GO

CREATE PROCEDURE GENERARTICKET
@COSTO INT,
@NROASIENTO INT,
@CODIGO VARCHAR(50)
AS 
INSERT TICKET VALUES
(@COSTO, @NROASIENTO, @CODIGO)
GO

CREATE PROCEDURE INSERTUSARIO
@USUARIO VARCHAR(45),
@PASS VARCHAR(45)
AS 
INSERT INTO USUARIO(Usuario,Contraseña) VALUES
(@USUARIO, @PASS)
GO

CREATE PROCEDURE GENERARBOLETERIA
@IDCOMPRA INT,
@IDCARTELERA INT,
@IDUSUARIO INT
AS 
INSERT BOLETERIA VALUES
(@IDCOMPRA, @IDCARTELERA, @IDUSUARIO)
GO

CREATE PROCEDURE LIST_COMPRA
AS
SELECT Id_ticket FROM TICKET
GO

CREATE PROCEDURE LIST_USUARIO
AS
SELECT Usuario FROM USUARIO
GO

CREATE PROCEDURE VER_PELICULA
AS
SELECT Id_peliculas,Titulo,Descripcion,Id_genero,Id_sala,Imagen 
FROM PELICULAS
GO

CREATE PROCEDURE VER_CARTELERA
AS
SELECT Titulo,Descripcion,fecha_Inicio,fecha_fin,costo FROM CARTELERA
inner join PELICULAS on CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
GO

CREATE PROCEDURE ELIMITE_PELICULA
@TITULOPELICULA VARCHAR(100)
AS
DELETE FROM PELICULAS
WHERE Titulo = @TITULOPELICULA
GO

CREATE PROCEDURE ACTUALIZAR_PELICULA
@IDPELICULA INT,
@TITULO VARCHAR(45),
@IMAGEN IMAGE,
@DESCRIPCION VARCHAR(45),
@GENEROID INT,
@SALAID INT
AS
UPDATE PELICULAS
SET Titulo=@TITULO, Imagen=@IMAGEN, Descripcion=@DESCRIPCION, Id_genero=@GENEROID,Id_sala=@SALAID
Where Id_peliculas = @IDPELICULA
GO

CREATE PROCEDURE PA_CARTELERA
@IDPELICULA INT
AS
SELECT Id_peliculas,fecha_Inicio,fecha_fin,costo FROM CARTELERA
WHERE Id_peliculas=@IDPELICULA
GO

CREATE PROCEDURE PA_CARTELERA_NOMBRE
@NOMBREPELICULA VARCHAR(45)
AS
SELECT PELICULAS.Id_peliculas,fecha_Inicio,fecha_fin,costo FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
WHERE Titulo=@NOMBREPELICULA
GO

CREATE PROCEDURE GENERATE_CODIGO
@NOMBREPELICULA VARCHAR(45)
AS
SELECT Id_cartelera,UPPER('#######'+ LEFT(Titulo,2) + RIGHT(Titulo,2)),costo FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
WHERE Titulo=@NOMBREPELICULA
GO

CREATE PROCEDURE ACTUALIZAR_CARTELERA
@IDPELICULA INT,
@FINICIO DATE,
@FFIN DATE,
@COSTO INT = NULL
AS
UPDATE CARTELERA
SET Id_peliculas=Isnull(@IDPELICULA,Id_peliculas), fecha_Inicio=Isnull(@FINICIO,fecha_Inicio), fecha_fin=Isnull(@FFIN,fecha_fin),
costo=Isnull(@COSTO,costo)
Where Id_peliculas = @IDPELICULA
GO

CREATE PROCEDURE BUSCARPELICULA
@Titulo VARCHAR(100)
AS
SELECT Id_peliculas,Titulo,Descripcion,Id_genero,Id_sala,Imagen FROM PELICULAS
WHERE Titulo =@Titulo
GO

CREATE PROCEDURE BUSCARCARTELERA
@NOMBREPELICULA VARCHAR(45)
AS
SELECT Titulo,Descripcion,fecha_Inicio,Id_cartelera FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
WHERE Titulo=@NOMBREPELICULA
GO

CREATE PROCEDURE ELIMITE_CARTELERA
@TITULOPELICULA VARCHAR(100)
AS
DELETE FROM CARTELERA
WHERE @TITULOPELICULA IN (SELECT Titulo FROM CARTELERA INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas )
GO

CREATE PROCEDURE CARTELERABOLETA
AS
select Id_boleteria,Titulo,costo from CARTELERA
INNER JOIN BOLETERIA ON CARTELERA.Id_cartelera = BOLETERIA.Id_cartelera
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
GO

--PARA SABER SI EL USUARIO ESTA ACTIVO O NO Y MANTENER SESIÓN--NO SALE 
--PARA SABER SI ES USUARIO O ADMINISTRADOR, NO SALE 

CREATE PROCEDURE STATUS
AS
SELECT tipo from USUARIO
GO

CREATE PROCEDURE ESONOES
AS
SELECT tipo from USUARIO
GO
