CREATE PROCEDURE LOGUEO
@USUARIO VARCHAR(45),
@PASS VARCHAR(8),
@SALIDA SMALLINT OUTPUT
AS


IF EXISTS(SELECT * FROM USUARIO WHERE USUARIO COLLATE Latin1_General_CS_AS =@USUARIO and Contraseña COLLATE Latin1_General_CS_AS =@PASS and estado = 1)
BEGIN
	SET @SALIDA =1 --ACTIVO
END
ELSE
	BEGIN

		IF EXISTS(SELECT * FROM USUARIO WHERE USUARIO COLLATE Latin1_General_CS_AS =@USUARIO and Contraseña COLLATE Latin1_General_CS_AS=@PASS and estado = 0)
		BEGIN
			SET @SALIDA =2 --NO ESTA ACTIVO
		END
		ELSE
		BEGIN

			IF EXISTS(SELECT * FROM USUARIO WHERE USUARIO COLLATE Latin1_General_CS_AS =@USUARIO and Contraseña COLLATE Latin1_General_CS_AS <> @PASS and estado = 1)
			BEGIN
				SET @SALIDA = 3 --El usuario existe y esta activo pero su contraseña es erronea
			END
			ELSE
			BEGIN
				SET @SALIDA = 4 --NO EXISTE
			END
		END
	END
GO


CREATE PROCEDURE LIST_GENERO
AS 
SELECT Nombre FROM GENERO
ORDER BY Nombre
GO


CREATE PROCEDURE LIST_SALA
AS
SELECT Nombre FROM SALA
GO

CREATE PROCEDURE LIST_CARTELERA
AS
SELECT Titulo,Id_cartelera  FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas=PELICULAS.Id_peliculas
GO


CREATE PROCEDURE PA_SALA
@Nombre VARCHAR(25)
AS 
SELECT Id_sala FROM SALA
WHERE Nombre=@Nombre
GO


CREATE PROCEDURE PA_GENERO
@Nombre VARCHAR(25)
AS 
SELECT Id_genero FROM GENERO
WHERE Nombre=@Nombre
GO

CREATE PROCEDURE PA_ASIENTO
@IDSALA INT
AS 
SELECT Numero FROM ASIENTO
WHERE Id_sala=@IDSALA
GO

CREATE PROCEDURE PA_USUARIO
@Nombre VARCHAR(45)
AS 
SELECT Id_usuario FROM USUARIO
WHERE Usuario=@Nombre
GO

CREATE PROCEDURE PA_PELICULA
@Titulo VARCHAR(45)
AS 
SELECT Id_peliculas FROM PELICULAS
WHERE Titulo=@Titulo
GO

CREATE PROCEDURE PA_TICKET
@IDTICKET INT
AS 
SELECT Id_ticket FROM TICKET
WHERE Id_ticket=@IDTICKET
GO


CREATE PROCEDURE INSERTPELICULA
@TITULO VARCHAR(45),
@IMAGEN IMAGE,
@DESCRIPCION VARCHAR(45),
@GENEROID INT,
@SALAID INT
AS 
INSERT PELICULAS VALUES
(@TITULO, @IMAGEN, @DESCRIPCION, @GENEROID, @SALAID)
GO




CREATE PROCEDURE LIST_PELICULA
AS 
SELECT Titulo FROM PELICULAS
ORDER BY Titulo
GO

CREATE PROCEDURE LIST_ASIENTOS
AS 
SELECT Numero FROM ASIENTO
GO


CREATE PROCEDURE INSERTCARTELERA
@IDPELICULA INT,
@FINICIO DATE,
@FFIN DATE,
@COST INT
AS 
INSERT CARTELERA VALUES
(@IDPELICULA, @FINICIO, @FFIN, @COST)
GO

CREATE PROCEDURE GENERARTICKET
@COSTO INT,
@NROASIENTO INT,
@CODIGO VARCHAR(50)
AS 
INSERT TICKET VALUES
(@COSTO, @NROASIENTO, @CODIGO)
GO


--
CREATE PROCEDURE GENERARBOLETERIA
@IDCOMPRA INT,
@IDCARTELERA INT,
@IDUSUARIO INT
AS 
INSERT BOLETERIA VALUES
(@IDCOMPRA, @IDCARTELERA, @IDUSUARIO)
GO

CREATE PROCEDURE LIST_COMPRA
AS
SELECT Id_ticket FROM TICKET
GO



CREATE PROCEDURE LIST_USUARIO
AS
SELECT Usuario FROM USUARIO
GO






CREATE PROCEDURE VER_PELICULA
AS
SELECT Id_peliculas,Titulo,Descripcion,Id_genero,Id_sala,Imagen FROM PELICULAS
GO

CREATE PROCEDURE VER_CARTELERA
AS
SELECT Titulo,Descripcion,fecha_Inicio,fecha_fin,costo FROM CARTELERA
inner join PELICULAS on CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
GO





CREATE PROCEDURE ELIMITE_PELICULA
@TITULOPELICULA VARCHAR(100)
AS
DELETE FROM PELICULAS
WHERE Titulo = @TITULOPELICULA
GO




CREATE PROCEDURE ACTUALIZAR_PELICULA
@IDPELICULA INT,
@TITULO VARCHAR(45),
@IMAGEN IMAGE,
@DESCRIPCION VARCHAR(45),
@GENEROID INT,
@SALAID INT
AS
UPDATE PELICULAS
SET Titulo=@TITULO, Imagen=@IMAGEN, Descripcion=@DESCRIPCION, Id_genero=@GENEROID,Id_sala=@SALAID
Where Id_peliculas = @IDPELICULA
GO

CREATE PROCEDURE PA_CARTELERA
@IDPELICULA INT
AS
SELECT Id_peliculas,fecha_Inicio,fecha_fin,costo FROM CARTELERA
WHERE Id_peliculas=@IDPELICULA
GO


CREATE PROCEDURE PA_CARTELERA_NOMBRE
@NOMBREPELICULA VARCHAR(45)
AS
SELECT PELICULAS.Id_peliculas,fecha_Inicio,fecha_fin,costo FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
WHERE Titulo=@NOMBREPELICULA
GO


CREATE PROCEDURE GENERATE_CODIGO
@NOMBREPELICULA VARCHAR(45)
AS
SELECT Id_cartelera,UPPER('#######'+ LEFT(Titulo,2) + RIGHT(Titulo,2)),costo FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
WHERE Titulo=@NOMBREPELICULA
GO


CREATE PROCEDURE ACTUALIZAR_CARTELERA
@IDPELICULA INT,
@FINICIO DATE,
@FFIN DATE,
@COSTO INT = NULL
AS
UPDATE CARTELERA
SET Id_peliculas=Isnull(@IDPELICULA,Id_peliculas), fecha_Inicio=Isnull(@FINICIO,fecha_Inicio), fecha_fin=Isnull(@FFIN,fecha_fin),
costo=Isnull(@COSTO,costo)
Where Id_peliculas = @IDPELICULA
GO


CREATE PROCEDURE BUSCARPELICULA
@Titulo VARCHAR(100)
AS
SELECT Id_peliculas,Titulo,Descripcion,Id_genero,Id_sala,Imagen FROM PELICULAS
WHERE Titulo =@Titulo
GO



CREATE PROCEDURE BUSCARCARTELERA
@NOMBREPELICULA VARCHAR(45)
AS
SELECT Titulo FROM CARTELERA
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
WHERE Titulo=@NOMBREPELICULA
GO




--PARA SABER SI EL USUARIO ESTA ACTIVO O NO Y MANTENER SESIÓN--NO SALE 
--PARA SABER SI ES USUARIO O ADMINISTRADOR, NO SALE 

CREATE PROCEDURE STATUS
AS
SELECT tipo from USUARIO
GO

CREATE PROCEDURE ESONOES
AS
SELECT tipo from USUARIO
GO







CREATE PROCEDURE ELIMITE_CARTELERA
@TITULOPELICULA VARCHAR(100)
AS
DELETE FROM CARTELERA
WHERE @TITULOPELICULA IN (SELECT Titulo FROM CARTELERA INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas )
GO



CREATE PROCEDURE CARTELERABOLETA
AS
select Usuario,Id_boleteria,Titulo,costo from CARTELERA
INNER JOIN BOLETERIA ON CARTELERA.Id_cartelera = BOLETERIA.Id_cartelera
INNER JOIN PELICULAS ON CARTELERA.Id_peliculas = PELICULAS.Id_peliculas
INNER JOIN USUARIO ON USUARIO.Id_usuario = Usuario.Id_usuario
go
